import type { IToolMeta } from "../types/tool";

export const TOOLS: IToolMeta[] = [
    {
        name: "JSON Formatter",
        slug: "json-formatter",
        description: "Format, validate, and beautify JSON instantly",
        icon: "Braces",
        category: "JSON",
        keywords: [
            "json formatter",
            "json beautifier",
            "json validator online",
            "format json",
            "json pretty print",
        ],
    },
    {
        name: "JSON Diff",
        slug: "json-diff",
        description: "Compare and find differences between JSON objects",
        icon: "GitCompare",
        category: "JSON",
        keywords: [
            "json diff",
            "json compare",
            "text diff online",
            "compare json objects",
            "diff checker",
        ],
    },
    {
        name: "JWT Decoder",
        slug: "jwt-decoder",
        description: "Decode and inspect JWT tokens instantly",
        icon: "KeyRound",
        category: "Security",
        keywords: [
            "jwt decoder",
            "jwt token decoder",
            "decode jwt online",
            "jwt debugger",
            "jwt parser",
        ],
    },
    {
        name: "Image Compressor",
        slug: "image-compressor",
        description: "Compress images in your browser — no uploads",
        icon: "ImageDown",
        category: "Images",
        keywords: [
            "image compressor",
            "compress images online",
            "bulk image compressor",
            "reduce image size",
            "image optimizer",
        ],
    },
    {
        name: "Base64 Encoder/Decoder",
        slug: "base64-encode-decode",
        description: "Encode and decode Base64 strings and files instantly",
        icon: "Binary",
        category: "Encoding",
        keywords: [
            "base64 encoder",
            "base64 decoder",
            "base64 encode online",
            "base64 decode online",
            "base64 converter",
            "base64 to text",
            "text to base64",
        ],
    },
    {
        name: "UUID Generator",
        slug: "uuid-generator",
        description: "Generate UUIDs v4 and v7 instantly — bulk or single",
        icon: "Fingerprint",
        category: "Generators",
        keywords: [
            "uuid generator",
            "uuid v4",
            "uuid v7",
            "generate uuid online",
            "guid generator",
            "unique id generator",
            "bulk uuid",
        ],
    },
    {
        name: "Regex Tester",
        slug: "regex-tester",
        description: "Test and debug regular expressions with live matching",
        icon: "Regex",
        category: "Text",
        keywords: [
            "regex tester",
            "regex101",
            "regular expression tester",
            "regex online",
            "regex debugger",
            "regex match",
            "regex replace",
        ],
    },
    {
        name: "Unix Timestamp Converter",
        slug: "unix-timestamp",
        description: "Convert between Unix timestamps and human-readable dates",
        icon: "Clock",
        category: "Converters",
        keywords: [
            "unix timestamp converter",
            "epoch converter",
            "timestamp to date",
            "date to timestamp",
            "unix time",
            "epoch time",
            "timestamp converter online",
        ],
    },
];

export const TOOL_CATEGORIES = [
    "JSON",
    "Security",
    "Images",
    "Encoding",
    "Generators",
    "Text",
    "Converters",
] as const;
export type ToolCategory = (typeof TOOL_CATEGORIES)[number];
